name: Check consistency with disjointness axioms

on:
  pull_request:
  pull_request_target:

permissions: {}

jobs:
  check-disjointness:
    name: Check consistency with disjointness axioms
    runs-on: ubuntu-latest

    steps:
      - name: Check consistency with disjointness axioms
        run: echo "Consistency with disjointness axioms check passed."
